services:
  telegram-monitor:
    build: .
    env_file: .env
    ports:
      - "3009:3000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6390:6379"
    restart: always
